-- =============================================================================
-- Patological — migração 002: porta o restante do banco do PatoVetZee
-- -----------------------------------------------------------------------------
-- Adiciona as 176 doenças que faltavam (o lote inicial tinha 39,
-- este arquivo completa o banco). "on conflict do nothing" torna seguro
-- rodar de novo. Cole este arquivo inteiro no SQL Editor do Supabase e rode.
-- =============================================================================

insert into public.patological_doencas (id, nome, especie, sistema, categorias, zoonose, contagiosa, letalidade, cura, reversibilidade) values
('diarreia_viral_bovina', 'Diarreia viral bovina (BVD)', 'Bovina', 'doencas_infecciosas_sistemicas', '{infecciosa_viral}', false, true, 55, false, 40),
('fiv_felina', 'Imunodeficiência viral felina (FIV)', 'Felina', 'doencas_infecciosas_sistemicas', '{infecciosa_viral}', false, true, 35, false, 45),
('toxoplasmose_felina', 'Toxoplasmose felina', 'Felina', 'doencas_infecciosas_sistemicas', '{infecciosa_parasitaria}', true, true, 40, true, 30),
('cardiomiopatia_hipertrofica_felina', 'Cardiomiopatia hipertrófica felina', 'Felina', 'sistema_cardiovascular', '{degenerativa,congenita_genetica}', false, false, 55, false, 80),
('defeito_septo_atrial_canino', 'Defeito do septo atrial (CIA)', 'Canina', 'sistema_cardiovascular', '{congenita_genetica}', false, false, 25, false, 60),
('defeito_septo_ventricular_canino', 'Defeito do septo ventricular (CIV)', 'Canina', 'sistema_cardiovascular', '{congenita_genetica}', false, false, 25, false, 60),
('endocardiose_valvar_canina', 'Endocardiose valvar (degeneração mixomatosa)', 'Canina', 'sistema_cardiovascular', '{degenerativa,congenita_genetica}', false, false, 55, false, 75),
('endocardite_bacteriana_canina', 'Endocardite bacteriana', 'Canina', 'sistema_cardiovascular', '{infecciosa_bacteriana}', false, false, 80, false, 70),
('endocardite_parasitaria_equina', 'Endocardite/arterite parasitária equina', 'Equina', 'sistema_cardiovascular', '{infecciosa_parasitaria,degenerativa}', false, true, 40, true, 55),
('persistencia_4_arco_aortico_direito_canina', 'Persistência do 4º arco aórtico direito (anel vascular)', 'Canina', 'sistema_cardiovascular', '{congenita_genetica}', false, false, 45, true, 50),
('reticulo_pericardite_traumatica_bovina', 'Retículo-pericardite traumática bovina', 'Bovina', 'sistema_cardiovascular', '{infecciosa_bacteriana}', false, false, 65, false, 75),
('tetralogia_fallot_canina', 'Tetralogia de Fallot', 'Canina', 'sistema_cardiovascular', '{congenita_genetica}', false, false, 75, false, 75),
('acidose_ruminal_bovina', 'Acidose ruminal em bovinos', 'Bovina', 'sistema_digestorio', '{toxica}', false, false, 55, true, 30),
('actinomicose_bovina', 'Actinomicose ("lumpy jaw")', 'Bovina', 'sistema_digestorio', '{infecciosa_bacteriana,degenerativa}', false, false, 10, false, 70),
('coccidiose_bovina', 'Coccidiose bovina', 'Bovina', 'sistema_digestorio', '{infecciosa_parasitaria}', false, true, 25, true, 15),
('corpo_estranho_gastrointestinal_canino', 'Corpo estranho gastrointestinal', 'Canina', 'sistema_digestorio', '{traumatica_mecanica}', false, false, 40, true, 20),
('deslocamento_abomaso_bovino', 'Deslocamento de abomaso', 'Bovina', 'sistema_digestorio', '{traumatica_mecanica}', false, false, 15, true, 15),
('ectima_contagioso_ovino', 'Ectima contagioso (dermatite pustular contagiosa)', 'Ovina', 'sistema_digestorio', '{infecciosa_viral}', true, true, 8, true, 10),
('espirocercose_canina', 'Espirocercose', 'Canina', 'sistema_digestorio', '{infecciosa_parasitaria}', false, true, 45, true, 40),
('gastrite_uremica_canina', 'Gastrite urêmica', 'Canina', 'sistema_digestorio', '{metabolica_endocrina}', false, false, 25, false, 55),
('giardiase_canina', 'Giardíase canina', 'Canina', 'sistema_digestorio', '{infecciosa_parasitaria}', true, true, 5, true, 5),
('habronemose_equina', 'Habronemose ("feridas de verão")', 'Equina', 'sistema_digestorio', '{infecciosa_parasitaria}', false, true, 3, true, 30),
('hemoncose_ovina', 'Hemoncose ("verme do barbeiro")', 'Ovina', 'sistema_digestorio', '{infecciosa_parasitaria}', false, true, 45, true, 25),
('intussuscepcao_canina', 'Intussuscepção intestinal', 'Canina', 'sistema_digestorio', '{traumatica_mecanica}', false, false, 50, true, 25),
('linfoma_intestinal_felino', 'Linfoma intestinal felino', 'Felina', 'sistema_digestorio', '{neoplasica}', false, false, 55, false, 70),
('megaesofago_idiopatico_canino', 'Megaesôfago idiopático/adquirido', 'Canina', 'sistema_digestorio', '{degenerativa}', false, false, 55, false, 75),
('melanoma_oral_canino', 'Melanoma oral canino', 'Canina', 'sistema_digestorio', '{neoplasica}', false, false, 70, false, 65),
('panleucopenia_felina', 'Panleucopenia felina', 'Felina', 'sistema_digestorio', '{infecciosa_viral}', false, true, 80, true, 25),
('peritonite_septica_canina', 'Peritonite séptica por perfuração', 'Canina', 'sistema_digestorio', '{infecciosa_bacteriana}', false, false, 80, true, 40),
('rotavirose_bovina', 'Rotavirose bovina', 'Bovina', 'sistema_digestorio', '{infecciosa_viral}', false, true, 30, true, 10),
('ulcera_gastrica_equina', 'Síndrome de úlcera gástrica equina (EGUS)', 'Equina', 'sistema_digestorio', '{toxica}', false, false, 5, true, 20),
('sindrome_zollinger_ellison_canina', 'Síndrome de Zollinger-Ellison (gastrinoma)', 'Canina', 'sistema_digestorio', '{neoplasica}', false, false, 55, false, 55),
('timpanismo_ruminal_bovino', 'Timpanismo ruminal', 'Bovina', 'sistema_digestorio', '{traumatica_mecanica}', false, false, 70, true, 10),
('ulcera_gastrica_canina', 'Úlcera péptica gastroduodenal', 'Canina', 'sistema_digestorio', '{toxica}', false, false, 30, true, 20),
('acromegalia_felina', 'Acromegalia felina', 'Felina', 'sistema_endocrino', '{neoplasica,degenerativa}', false, false, 55, false, 70),
('bocio_bovino', 'Bócio (hiperplasia tireoidiana por deficiência de iodo)', 'Bovina', 'sistema_endocrino', '{metabolica_endocrina}', false, false, 35, true, 20),
('carcinoma_tireoide_canino', 'Carcinoma de tireoide', 'Canina', 'sistema_endocrino', '{neoplasica}', false, false, 50, true, 40),
('diabetes_insipidus_central_canina', 'Diabetes insipidus central', 'Canina', 'sistema_endocrino', '{metabolica_endocrina}', false, false, 10, false, 30),
('diabetes_insipidus_nefrogenica_canina', 'Diabetes insipidus nefrogênica', 'Canina', 'sistema_endocrino', '{congenita_genetica}', false, false, 10, false, 35),
('diabetes_mellitus_canina', 'Diabetes mellitus canina', 'Canina', 'sistema_endocrino', '{degenerativa}', false, false, 65, false, 45),
('feocromocitoma_canino', 'Feocromocitoma', 'Canina', 'sistema_endocrino', '{neoplasica}', false, false, 55, true, 40),
('hiperadrenocorticismo_iatrogenico_canino', 'Hiperadrenocorticismo iatrogênico', 'Canina', 'sistema_endocrino', '{metabolica_endocrina}', false, false, 15, true, 20),
('hipercalcemia_maligna_canina', 'Hipercalcemia da malignidade (pseudo-hiperparatireoidismo)', 'Canina', 'sistema_endocrino', '{neoplasica,metabolica_endocrina}', false, false, 65, false, 45),
('hiperparatireoidismo_primario_canino', 'Hiperparatireoidismo primário', 'Canina', 'sistema_endocrino', '{neoplasica}', false, false, 10, true, 25),
('hiperparatireoidismo_nutricional_canino', 'Hiperparatireoidismo secundário nutricional', 'Canina', 'sistema_endocrino', '{degenerativa,metabolica_endocrina}', false, false, 10, true, 45),
('hiperparatireoidismo_renal_canino', 'Hiperparatireoidismo secundário renal', 'Canina', 'sistema_endocrino', '{degenerativa,metabolica_endocrina}', false, false, 35, false, 60),
('hipertireoidismo_felino', 'Hipertireoidismo felino', 'Felina', 'sistema_endocrino', '{neoplasica}', false, false, 45, true, 25),
('hipoadrenocorticismo_canino', 'Hipoadrenocorticismo (Addison)', 'Canina', 'sistema_endocrino', '{metabolica_endocrina}', false, false, 75, false, 15),
('hipoparatireoidismo_canino', 'Hipoparatireoidismo', 'Canina', 'sistema_endocrino', '{metabolica_endocrina}', false, false, 60, false, 20),
('hipotireoidismo_canino', 'Hipotireoidismo canino', 'Canina', 'sistema_endocrino', '{metabolica_endocrina}', false, false, 10, false, 25),
('nanismo_hipofisario_canino', 'Nanismo hipofisário', 'Canina', 'sistema_endocrino', '{degenerativa,congenita_genetica}', false, false, 25, false, 80),
('leucose_enzootica_bovina', 'Leucose enzoótica bovina', 'Bovina', 'sistema_hematopoietico_linfatico', '{infecciosa_viral,neoplasica}', false, true, 15, false, 55),
('carcinoma_hepatocelular_canino', 'Carcinoma hepatocelular', 'Canina', 'sistema_hepatobiliar', '{neoplasica}', false, false, 45, true, 55),
('cisticercose_bovina', 'Cisticercose bovina (Cysticercus bovis)', 'Bovina', 'sistema_hepatobiliar', '{infecciosa_parasitaria}', true, true, 2, false, 20),
('colangiocarcinoma_felino', 'Colangiocarcinoma', 'Felina', 'sistema_hepatobiliar', '{neoplasica}', false, false, 65, false, 65),
('colangite_felina', 'Colangite felina', 'Felina', 'sistema_hepatobiliar', '{degenerativa}', false, false, 30, false, 60),
('complexo_rumenite_abscesso_hepatico_bovino', 'Complexo rumenite-abscesso hepático', 'Bovina', 'sistema_hepatobiliar', '{infecciosa_bacteriana}', false, false, 35, false, 60),
('fasciolose_bovina', 'Fasciolose (Fasciola hepatica)', 'Bovina', 'sistema_hepatobiliar', '{infecciosa_parasitaria,degenerativa}', true, true, 20, true, 45),
('fotossensibilizacao_hepatogena_bovina', 'Fotossensibilização hepatógena', 'Bovina', 'sistema_hepatobiliar', '{toxica}', false, false, 40, false, 55),
('hepatite_infecciosa_canina', 'Hepatite infecciosa canina (adenovírus CAV-1)', 'Canina', 'sistema_hepatobiliar', '{infecciosa_viral}', false, true, 60, true, 25),
('hepatopatia_cobre_canina', 'Hepatopatia por acúmulo de cobre', 'Canina', 'sistema_hepatobiliar', '{degenerativa,congenita_genetica}', false, false, 55, false, 80),
('senecio_intoxicacao_bovina', 'Intoxicação por Senecio spp. (seneciose)', 'Bovina', 'sistema_hepatobiliar', '{degenerativa}', false, true, 70, false, 85),
('intoxicacao_xilitol_canina', 'Intoxicação por xilitol', 'Canina', 'sistema_hepatobiliar', '{toxica}', false, false, 60, true, 30),
('shunt_portossistemico_congenito_canino', 'Shunt portossistêmico congênito', 'Canina', 'sistema_hepatobiliar', '{congenita_genetica}', false, false, 45, true, 60),
('toxemia_da_prenhez_ovina', 'Toxemia da prenhez (ovinos)', 'Ovina', 'sistema_hepatobiliar', '{metabolica_endocrina}', false, false, 75, true, 30),
('triadite_felina', 'Triadite felina', 'Felina', 'sistema_hepatobiliar', '{imunomediada}', false, false, 45, false, 55),
('artrite_por_lentivirus_ovina', 'Artrite por lentivírus de pequenos ruminantes (Maedi-Visna)', 'Ovina', 'sistema_musculoesqueletico', '{infecciosa_viral,degenerativa}', false, true, 15, false, 80),
('artrite_reumatoide_canina', 'Artrite reumatoide (imunomediada)', 'Canina', 'sistema_musculoesqueletico', '{degenerativa}', false, false, 10, false, 75),
('artrite_septica_bovina', 'Artrite séptica (via onfaloflebite)', 'Bovina', 'sistema_musculoesqueletico', '{infecciosa_bacteriana}', false, true, 15, true, 55),
('carbunculo_sintomatico_bovino', 'Carbúnculo sintomático ("blackleg", Clostridium chauvoei)', 'Bovina', 'sistema_musculoesqueletico', '{infecciosa_bacteriana}', false, true, 90, false, 95),
('distrofia_muscular_canina', 'Distrofia muscular (mutação da distrofina)', 'Canina', 'sistema_musculoesqueletico', '{degenerativa,congenita_genetica}', false, false, 35, false, 95),
('doenca_musculo_branco_ovina', 'Doença do músculo branco (deficiência de selênio/vit. E)', 'Ovina', 'sistema_musculoesqueletico', '{metabolica_endocrina}', false, false, 45, true, 45),
('edema_maligno_equino', 'Edema maligno (Clostridium septicum)', 'Equina', 'sistema_musculoesqueletico', '{infecciosa_bacteriana}', false, true, 90, false, 90),
('miopatia_por_esforco_equina', 'Miopatia por esforço ("mal da segunda-feira"/rabdomiólise)', 'Equina', 'sistema_musculoesqueletico', '{congenita_genetica}', false, false, 30, false, 35),
('hipertrofia_muscular_congenita_bovina', 'Musculatura dupla (hipertrofia muscular congênita)', 'Bovina', 'sistema_musculoesqueletico', '{congenita_genetica}', false, false, 5, false, 100),
('neosporose_canina', 'Neosporose (Neospora caninum)', 'Canina', 'sistema_musculoesqueletico', '{infecciosa_parasitaria}', false, true, 35, false, 65),
('osteoartrite_canina', 'Osteoartrite / doença articular degenerativa', 'Canina', 'sistema_musculoesqueletico', '{degenerativa}', false, false, 3, false, 80),
('osteodistrofia_fibrosa_equina', 'Osteodistrofia fibrosa ("bran disease")', 'Equina', 'sistema_musculoesqueletico', '{degenerativa}', false, false, 10, true, 50),
('osteogenese_imperfeita_canina', 'Osteogênese imperfeita', 'Canina', 'sistema_musculoesqueletico', '{congenita_genetica}', false, false, 10, false, 90),
('osteoma_equino', 'Osteoma (mandíbula)', 'Equina', 'sistema_musculoesqueletico', '{neoplasica}', false, false, 3, true, 40),
('osteomielite_bacteriana_bovina', 'Osteomielite bacteriana (via onfaloflebite)', 'Bovina', 'sistema_musculoesqueletico', '{infecciosa_bacteriana}', false, true, 20, false, 70),
('osteopetrose_canina', 'Osteopetrose', 'Canina', 'sistema_musculoesqueletico', '{degenerativa,congenita_genetica}', false, false, 20, false, 85),
('purpura_hemorragica_equina', 'Púrpura hemorrágica (vasculite imunomediada pós-estrangúlio)', 'Equina', 'sistema_musculoesqueletico', '{imunomediada}', false, false, 45, true, 40),
('tromboembolismo_arterial_felino', 'Tromboembolismo arterial ("saddle thrombus")', 'Felina', 'sistema_musculoesqueletico', '{traumatica_mecanica}', false, false, 80, false, 85),
('encefalopatia_hepatica_canina', 'Encefalopatia hepática', 'Canina', 'sistema_nervoso', '{metabolica_endocrina}', false, false, 55, false, 40),
('hidrocefalia_congenita_canina', 'Hidrocefalia congênita', 'Canina', 'sistema_nervoso', '{congenita_genetica}', false, false, 25, false, 85),
('intoxicacao_sal_bovina', 'Intoxicação por NaCl (síndrome da privação de água)', 'Bovina', 'sistema_nervoso', '{toxica}', false, false, 55, true, 45),
('leucoencefalomalacia_equina', 'Leucoencefalomalácia equina ("moldy corn disease")', 'Equina', 'sistema_nervoso', '{infecciosa_fungica}', false, false, 85, false, 90),
('meningite_bacteriana_neonatal_equina', 'Meningite bacteriana neonatal (sepse do potro)', 'Equina', 'sistema_nervoso', '{infecciosa_bacteriana}', false, true, 80, true, 45),
('mieloencefalite_protozoaria_equina', 'Mieloencefalite protozoária equina (EPM)', 'Equina', 'sistema_nervoso', '{infecciosa_parasitaria}', false, true, 25, false, 60),
('polioencefalomalacia_bovina', 'Polioencefalomalácia (deficiência de tiamina/excesso de enxofre)', 'Bovina', 'sistema_nervoso', '{metabolica_endocrina}', false, false, 50, true, 55),
('raiva_bovina', 'Raiva bovina (raiva dos herbívoros)', 'Bovina', 'sistema_nervoso', '{infecciosa_viral}', true, true, 100, false, 100),
('raiva_equina', 'Raiva equina (raiva dos herbívoros)', 'Equina', 'sistema_nervoso', '{infecciosa_viral}', true, true, 100, false, 100),
('scrapie_ovina', 'Scrapie (príon)', 'Ovina', 'sistema_nervoso', '{degenerativa,congenita_genetica}', false, true, 100, false, 100),
('adenocarcinoma_pancreatico_canino', 'Adenocarcinoma pancreático', 'Canina', 'sistema_pancreatico', '{neoplasica}', false, false, 85, false, 70),
('pancreatite_aguda_canina', 'Pancreatite aguda canina', 'Canina', 'sistema_pancreatico', '{toxica}', false, false, 50, true, 30),
('pancreatite_cronica_felina', 'Pancreatite crônica felina', 'Felina', 'sistema_pancreatico', '{degenerativa}', false, false, 20, false, 65),
('brucelose_canina', 'Brucelose canina', 'Canina', 'sistema_reprodutor', '{infecciosa_bacteriana}', true, true, 10, false, 45),
('carcinoma_celulas_escamosas_genital_equino', 'Carcinoma de células escamosas genital (equino)', 'Equina', 'sistema_reprodutor', '{neoplasica}', false, false, 20, true, 40),
('carcinoma_inflamatorio_mamario_canino', 'Carcinoma inflamatório mamário canino', 'Canina', 'sistema_reprodutor', '{neoplasica}', false, false, 90, false, 70),
('carcinoma_mamario_canino', 'Carcinoma mamário canino', 'Canina', 'sistema_reprodutor', '{neoplasica}', false, false, 55, false, 55),
('cisto_folicular_ovariano_bovino', 'Cisto folicular ovariano bovino', 'Bovina', 'sistema_reprodutor', '{metabolica_endocrina}', false, false, 2, true, 15),
('endometrite_cronica_bovina', 'Endometrite crônica bovina', 'Bovina', 'sistema_reprodutor', '{infecciosa_bacteriana}', false, false, 5, true, 30),
('fibropapiloma_peniano_bovino', 'Fibropapiloma peniano bovino', 'Bovina', 'sistema_reprodutor', '{infecciosa_viral,neoplasica}', false, true, 2, true, 10),
('freemartinismo_bovina', 'Freemartinismo', 'Bovina', 'sistema_reprodutor', '{congenita_genetica}', false, false, 0, false, 100),
('hiperplasia_endometrial_cistica_canina', 'Hiperplasia endometrial cística canina', 'Canina', 'sistema_reprodutor', '{metabolica_endocrina}', false, false, 5, true, 20),
('hiperplasia_fibroadenomatosa_mamaria_felina', 'Hiperplasia fibroadenomatosa mamária felina', 'Felina', 'sistema_reprodutor', '{metabolica_endocrina}', false, false, 5, true, 15),
('hiperplasia_prostatica_benigna_canina', 'Hiperplasia prostática benigna canina', 'Canina', 'sistema_reprodutor', '{metabolica_endocrina}', false, false, 2, true, 15),
('leiomioma_uterino_canino', 'Leiomioma uterino canino', 'Canina', 'sistema_reprodutor', '{neoplasica}', false, false, 3, true, 10),
('mastite_bovina', 'Mastite bovina', 'Bovina', 'sistema_reprodutor', '{infecciosa_bacteriana}', false, true, 15, true, 25),
('metrite_puerperal_bovina', 'Metrite puerperal bovina', 'Bovina', 'sistema_reprodutor', '{infecciosa_bacteriana}', false, false, 55, true, 25),
('orquite_bacteriana_canina', 'Orquite/epididimite bacteriana canina', 'Canina', 'sistema_reprodutor', '{infecciosa_bacteriana}', false, false, 15, true, 30),
('piometra_bovina', 'Piometra bovina (piometrite)', 'Bovina', 'sistema_reprodutor', '{infecciosa_bacteriana}', false, false, 10, true, 20),
('prolapso_uterino_bovino', 'Prolapso uterino bovino', 'Bovina', 'sistema_reprodutor', '{traumatica_mecanica}', false, false, 60, true, 25),
('prostatite_canina', 'Prostatite canina', 'Canina', 'sistema_reprodutor', '{infecciosa_bacteriana}', false, false, 35, true, 25),
('pseudociese_canina', 'Pseudociese canina', 'Canina', 'sistema_reprodutor', '{metabolica_endocrina}', false, false, 0, true, 5),
('seminoma_canino', 'Seminoma canino', 'Canina', 'sistema_reprodutor', '{neoplasica}', false, false, 8, true, 20),
('torcao_uterina_bovina', 'Torção uterina bovina', 'Bovina', 'sistema_reprodutor', '{traumatica_mecanica}', false, false, 70, true, 20),
('tumor_celulas_granulosa_equino', 'Tumor de células da granulosa (equino)', 'Equina', 'sistema_reprodutor', '{neoplasica}', false, false, 10, true, 30),
('tumor_celulas_leydig_canino', 'Tumor de células de Leydig canino', 'Canina', 'sistema_reprodutor', '{neoplasica}', false, false, 3, true, 15),
('tumor_celulas_sertoli_canino', 'Tumor de células de Sertoli canino', 'Canina', 'sistema_reprodutor', '{neoplasica}', false, false, 45, false, 45),
('tumor_mamario_benigno_canino', 'Tumor mamário benigno canino', 'Canina', 'sistema_reprodutor', '{neoplasica}', false, false, 3, true, 10),
('adenocarcinoma_pulmonar_canino', 'Adenocarcinoma pulmonar canino', 'Canina', 'sistema_respiratorio', '{neoplasica}', false, false, 65, false, 65),
('broncopneumonia_bacteriana_canina', 'Broncopneumonia bacteriana canina', 'Canina', 'sistema_respiratorio', '{infecciosa_bacteriana}', false, true, 40, true, 20),
('difteria_bezerros', 'Difteria dos bezerros', 'Bovina', 'sistema_respiratorio', '{infecciosa_bacteriana}', false, true, 45, true, 30),
('hemorragia_pulmonar_induzida_exercicio_equina', 'Hemorragia pulmonar induzida por exercício (equina)', 'Equina', 'sistema_respiratorio', '{degenerativa}', false, false, 10, false, 55),
('micose_bolsa_gutural_equina', 'Micose de bolsa gutural equina', 'Equina', 'sistema_respiratorio', '{infecciosa_fungica}', false, false, 45, true, 45),
('neoplasia_nasal_canina', 'Neoplasia nasal canina', 'Canina', 'sistema_respiratorio', '{neoplasica}', false, false, 60, false, 65),
('piotorax_felino', 'Piotórax felino', 'Felina', 'sistema_respiratorio', '{infecciosa_bacteriana}', false, false, 65, true, 35),
('pneumonia_fibrinosa_bovina', 'Pneumonia fibrinosa bovina ("febre do transporte")', 'Bovina', 'sistema_respiratorio', '{infecciosa_bacteriana}', false, true, 50, true, 30),
('rinotraqueite_infecciosa_bovina', 'Rinotraqueíte infecciosa bovina (IBR)', 'Bovina', 'sistema_respiratorio', '{infecciosa_viral}', false, true, 20, false, 30),
('rodococose_equina', 'Rodococose equina (potros)', 'Equina', 'sistema_respiratorio', '{infecciosa_bacteriana}', false, true, 55, true, 35),
('verminose_pulmonar_bovina', 'Verminose pulmonar bovina', 'Bovina', 'sistema_respiratorio', '{infecciosa_parasitaria}', false, true, 35, true, 25),
('adenite_sebacea_canina', 'Adenite sebácea', 'Canina', 'sistema_tegumentar', '{degenerativa,congenita_genetica}', false, false, 3, false, 65),
('carcinoma_celulas_escamosas_cutaneo', 'Carcinoma de células escamosas (cutâneo)', 'Felina', 'sistema_tegumentar', '{neoplasica}', false, false, 25, true, 75),
('carcinoma_sebaceo_canino', 'Carcinoma sebáceo', 'Canina', 'sistema_tegumentar', '{neoplasica}', false, false, 15, true, 40),
('complexo_granuloma_eosinofilico_felino', 'Complexo granuloma eosinofílico felino', 'Felina', 'sistema_tegumentar', '{imunomediada}', false, false, 3, false, 30),
('criptococose_felina', 'Criptococose', 'Felina', 'sistema_tegumentar', '{infecciosa_fungica}', false, true, 40, true, 45),
('demodicose_canina', 'Demodicose (sarna demodécica)', 'Canina', 'sistema_tegumentar', '{infecciosa_parasitaria}', false, false, 5, false, 35),
('dermatite_malassezia_canina', 'Dermatite generalizada por Malassezia spp.', 'Canina', 'sistema_tegumentar', '{infecciosa_fungica,degenerativa}', false, false, 2, false, 35),
('dermatite_solar_canina', 'Dermatite solar (actínica) canina', 'Canina', 'sistema_tegumentar', '{degenerativa}', false, false, 5, false, 60),
('dermatite_herpesvirus_felino', 'Dermatite ulcerativa facial por herpesvírus felino', 'Felina', 'sistema_tegumentar', '{infecciosa_viral}', false, true, 5, false, 35),
('dermatofitose_felina', 'Dermatofitose ("ringworm")', 'Felina', 'sistema_tegumentar', '{infecciosa_fungica}', true, true, 2, true, 10),
('escabiose_sarna_sarcoptica_canina', 'Escabiose (sarna sarcóptica)', 'Canina', 'sistema_tegumentar', '{infecciosa_parasitaria}', true, true, 3, true, 10),
('esporotricose_felina', 'Esporotricose', 'Felina', 'sistema_tegumentar', '{infecciosa_fungica}', true, true, 20, true, 40),
('hemangiossarcoma_cutaneo_canino', 'Hemangiossarcoma cutâneo', 'Canina', 'sistema_tegumentar', '{neoplasica}', false, false, 35, true, 45),
('histiocitoma_cutaneo_canino', 'Histiocitoma cutâneo canino', 'Canina', 'sistema_tegumentar', '{neoplasica}', false, false, 1, true, 5),
('histoplasmose_canina', 'Histoplasmose', 'Canina', 'sistema_tegumentar', '{infecciosa_fungica}', false, true, 45, true, 45),
('linfoma_cutaneo_epiteliotropico_canino', 'Linfoma cutâneo epiteliotrópico', 'Canina', 'sistema_tegumentar', '{neoplasica}', false, false, 60, false, 70),
('lipoma_canino', 'Lipoma subcutâneo', 'Canina', 'sistema_tegumentar', '{neoplasica}', false, false, 1, true, 5),
('lupus_eritematoso_discoide_canino', 'Lúpus eritematoso discoide', 'Canina', 'sistema_tegumentar', '{degenerativa}', false, false, 3, false, 60),
('melanoma_cutaneo_canino', 'Melanoma cutâneo canino', 'Canina', 'sistema_tegumentar', '{neoplasica}', false, false, 15, true, 30),
('otite_externa_malassezia', 'Otite externa por Malassezia spp.', 'Canina', 'sistema_tegumentar', '{infecciosa_fungica}', false, false, 3, true, 10),
('paniculite_canina', 'Paniculite (pós-vacinal, traumática ou estéril idiopática)', 'Canina', 'sistema_tegumentar', '{imunomediada}', false, false, 3, true, 25),
('papiloma_cutaneo_viral_canino', 'Papiloma cutâneo viral', 'Canina', 'sistema_tegumentar', '{infecciosa_viral,neoplasica}', false, true, 1, true, 5),
('penfigo_foliaceo_canino', 'Pênfigo foliáceo', 'Canina', 'sistema_tegumentar', '{degenerativa}', false, false, 15, false, 70),
('piodermite_bacteriana_canina', 'Piodermite bacteriana (superficial/profunda)', 'Canina', 'sistema_tegumentar', '{infecciosa_bacteriana}', false, false, 3, true, 10),
('plasmocitoma_cutaneo_canino', 'Plasmocitoma cutâneo', 'Canina', 'sistema_tegumentar', '{neoplasica}', false, false, 5, true, 10),
('sarna_notoedrica_felina', 'Sarna notoédrica felina', 'Felina', 'sistema_tegumentar', '{infecciosa_parasitaria}', true, true, 3, true, 10),
('tumor_benigno_anexos_cutaneos_canino', 'Tumor benigno de anexos cutâneos (tricoepitelioma/pilomatricoma/adenoma sebáceo)', 'Canina', 'sistema_tegumentar', '{neoplasica}', false, false, 2, true, 15),
('vasculite_cutanea_imunomediada_canina', 'Vasculite cutânea imunomediada', 'Canina', 'sistema_tegumentar', '{imunomediada}', false, false, 10, false, 55),
('carcinoma_celulas_transicionais_canino', 'Carcinoma de células transicionais (bexiga)', 'Canina', 'sistema_urinario', '{neoplasica}', false, false, 55, false, 60),
('cistite_bacteriana_canina', 'Cistite bacteriana', 'Canina', 'sistema_urinario', '{infecciosa_bacteriana}', false, false, 3, true, 5),
('cistite_idiopatica_felina', 'Cistite idiopática felina (FLUTD)', 'Felina', 'sistema_urinario', '{metabolica_endocrina}', false, false, 5, false, 15),
('drc_canina', 'Doença renal crônica canina', 'Canina', 'sistema_urinario', '{degenerativa}', false, false, 70, false, 85),
('glomerulonefrite_imunomediada_canina', 'Glomerulonefrite imunomediada canina', 'Canina', 'sistema_urinario', '{degenerativa}', false, false, 55, false, 65),
('hidronefrose_equina', 'Hidronefrose', 'Equina', 'sistema_urinario', '{degenerativa}', false, false, 15, true, 65),
('necrose_tubular_aguda_felina', 'Necrose tubular aguda felina', 'Felina', 'sistema_urinario', '{toxica}', false, false, 80, true, 40),
('necrose_tubular_aguda_toxica_canina', 'Necrose tubular aguda por intoxicação (uva/passas, etilenoglicol)', 'Canina', 'sistema_urinario', '{toxica}', false, false, 85, true, 35),
('nefroblastoma_canino', 'Nefroblastoma (tumor de Wilms)', 'Canina', 'sistema_urinario', '{neoplasica}', false, false, 55, true, 45),
('nefrolitiase_felina', 'Nefrolitíase (cálculos renais)', 'Felina', 'sistema_urinario', '{traumatica_mecanica}', false, false, 15, true, 20),
('pielonefrite_felina', 'Pielonefrite', 'Felina', 'sistema_urinario', '{infecciosa_bacteriana,degenerativa}', false, false, 30, true, 30),
('pielonefrite_bovina', 'Pielonefrite (Corynebacterium renale)', 'Bovina', 'sistema_urinario', '{infecciosa_bacteriana}', false, true, 45, true, 35),
('poliquistose_renal_felina', 'Poliquistose renal (PKD)', 'Felina', 'sistema_urinario', '{degenerativa,congenita_genetica}', false, false, 30, false, 90),
('urolitiase_canina', 'Urolitíase (struvita/oxalato de cálcio)', 'Canina', 'sistema_urinario', '{traumatica_mecanica}', false, false, 10, true, 15),
('urolitiase_obstrutiva_ovina', 'Urolitíase obstrutiva', 'Ovina', 'sistema_urinario', '{traumatica_mecanica}', false, false, 65, true, 35)
on conflict (id) do nothing;
