-- =============================================================================
-- PatoVetZee — adiciona 6 doenças renais (sistema urinário: 12 -> 18)
-- -----------------------------------------------------------------------------
-- Cole este arquivo inteiro no SQL Editor do Supabase e rode.
-- "on conflict (id) do nothing" faz o script ser seguro de rodar de novo
-- (não duplica nem sobrescreve se algum id já existir).
-- =============================================================================

insert into public.doencas (id, nome, especie, sistema, dica, parametros_binarios, parametros_graduais)
values ('drc_canina', 'Doença renal crônica canina', 'Canina', 'sistema_urinario', null, '{"zoonose":false,"doenca_viral":false,"doenca_bacteriana":false,"doenca_parasitaria":false,"doenca_fungica":false,"associada_uso_hormonios":false,"etiologia_hereditaria_genetica":false,"transmitida_por_vetores":false,"contagiosa_contato_direto":false,"transmissao_ambiental_fomites":false,"transmissao_vertical_transplacentaria":false,"requer_notificacao_obrigatoria":false,"maior_prevalencia_felinos":false,"predisposicao_racial_reconhecida":true,"maior_prevalencia_animais_idosos":true,"maior_prevalencia_filhotes_jovens":false,"predisposicao_femeas_nao_castradas":false,"associada_obesidade":false,"maior_prevalencia_ambientes_coletivos":false,"doenca_neoplasica":false,"causa_hemorragia":false,"lesao_caracteristicamente_multissistemica":false,"processo_inflamatorio_predominante":false,"lesao_potencialmente_metastatica":false,"causa_alteracao_degenerativa_cronica":true,"sinais_gastrointestinais_proeminentes":true,"sinais_respiratorios_proeminentes":false,"sinais_dermatologicos_proeminentes":false,"sinais_musculoesqueleticos_proeminentes":false,"linfonodomegalia_frequente":false,"febre_frequente":false,"sinais_sistemicos_inespecificos_comuns":true,"perda_peso_ou_caquexia_frequente":true,"diagnostico_por_exame_sorologico":false,"diagnostico_por_citologia_biopsia":true,"diagnostico_por_imagem_essencial":false,"diagnostico_laboratorial_bioquimico_essencial":true,"diagnostico_definitivo_requer_histopatologia":false,"teste_rapido_disponivel_rotina":true,"alteracoes_hematologicas_caracteristicas":true,"tratamento_cirurgico_indicado":false,"tratamento_quimioterapico_indicado":false,"tratamento_com_antimicrobianos_especificos":false,"tratamento_essencialmente_de_suporte":true,"tratamento_topico_frequente":false,"tratamento_exclusivamente_paliativo":false,"requer_tratamento_continuo_longo_prazo":true,"prognostico_favoravel":false,"doenca_potencialmente_fatal_sem_tratamento":true,"risco_recidiva_relevante":false,"cura_definitiva_possivel":false,"doenca_cronica_progressiva":true,"doenca_metabolica":false}'::jsonb, '{"letalidade_nao_tratada":70,"velocidade_progressao":30,"custo_complexidade_diagnostica":55,"impacto_qualidade_vida":65,"disseminacao_ambiente_coletivo":0,"relevancia_diferencial_rotina":60,"invasividade_tratamento_padrao":30,"impacto_economico_tratamento":60}'::jsonb)
on conflict (id) do nothing;

insert into public.doencas (id, nome, especie, sistema, dica, parametros_binarios, parametros_graduais)
values ('nefropatia_leishmaniose_canina', 'Nefropatia da leishmaniose visceral canina', 'Canina', 'sistema_urinario', null, '{"zoonose":true,"doenca_viral":false,"doenca_bacteriana":false,"doenca_parasitaria":true,"doenca_fungica":false,"associada_uso_hormonios":false,"etiologia_hereditaria_genetica":false,"transmitida_por_vetores":true,"contagiosa_contato_direto":false,"transmissao_ambiental_fomites":false,"transmissao_vertical_transplacentaria":true,"requer_notificacao_obrigatoria":true,"maior_prevalencia_felinos":false,"predisposicao_racial_reconhecida":false,"maior_prevalencia_animais_idosos":false,"maior_prevalencia_filhotes_jovens":false,"predisposicao_femeas_nao_castradas":false,"associada_obesidade":false,"maior_prevalencia_ambientes_coletivos":true,"doenca_neoplasica":false,"causa_hemorragia":false,"lesao_caracteristicamente_multissistemica":true,"processo_inflamatorio_predominante":true,"lesao_potencialmente_metastatica":false,"causa_alteracao_degenerativa_cronica":true,"sinais_gastrointestinais_proeminentes":false,"sinais_respiratorios_proeminentes":false,"sinais_dermatologicos_proeminentes":true,"sinais_musculoesqueleticos_proeminentes":false,"linfonodomegalia_frequente":true,"febre_frequente":false,"sinais_sistemicos_inespecificos_comuns":true,"perda_peso_ou_caquexia_frequente":true,"diagnostico_por_exame_sorologico":true,"diagnostico_por_citologia_biopsia":true,"diagnostico_por_imagem_essencial":false,"diagnostico_laboratorial_bioquimico_essencial":true,"diagnostico_definitivo_requer_histopatologia":false,"teste_rapido_disponivel_rotina":true,"alteracoes_hematologicas_caracteristicas":true,"tratamento_cirurgico_indicado":false,"tratamento_quimioterapico_indicado":false,"tratamento_com_antimicrobianos_especificos":true,"tratamento_essencialmente_de_suporte":false,"tratamento_topico_frequente":false,"tratamento_exclusivamente_paliativo":false,"requer_tratamento_continuo_longo_prazo":true,"prognostico_favoravel":false,"doenca_potencialmente_fatal_sem_tratamento":true,"risco_recidiva_relevante":true,"cura_definitiva_possivel":false,"doenca_cronica_progressiva":true,"doenca_metabolica":false}'::jsonb, '{"letalidade_nao_tratada":70,"velocidade_progressao":35,"custo_complexidade_diagnostica":50,"impacto_qualidade_vida":65,"disseminacao_ambiente_coletivo":25,"relevancia_diferencial_rotina":55,"invasividade_tratamento_padrao":20,"impacto_economico_tratamento":60}'::jsonb)
on conflict (id) do nothing;

insert into public.doencas (id, nome, especie, sistema, dica, parametros_binarios, parametros_graduais)
values ('necrose_tubular_aguda_toxica_canina', 'Necrose tubular aguda por intoxicação (uva/passas, etilenoglicol)', 'Canina', 'sistema_urinario', null, '{"zoonose":false,"doenca_viral":false,"doenca_bacteriana":false,"doenca_parasitaria":false,"doenca_fungica":false,"associada_uso_hormonios":false,"etiologia_hereditaria_genetica":false,"transmitida_por_vetores":false,"contagiosa_contato_direto":false,"transmissao_ambiental_fomites":false,"transmissao_vertical_transplacentaria":false,"requer_notificacao_obrigatoria":false,"maior_prevalencia_felinos":false,"predisposicao_racial_reconhecida":false,"maior_prevalencia_animais_idosos":false,"maior_prevalencia_filhotes_jovens":false,"predisposicao_femeas_nao_castradas":false,"associada_obesidade":false,"maior_prevalencia_ambientes_coletivos":false,"doenca_neoplasica":false,"causa_hemorragia":false,"lesao_caracteristicamente_multissistemica":false,"processo_inflamatorio_predominante":false,"lesao_potencialmente_metastatica":false,"causa_alteracao_degenerativa_cronica":false,"sinais_gastrointestinais_proeminentes":true,"sinais_respiratorios_proeminentes":false,"sinais_dermatologicos_proeminentes":false,"sinais_musculoesqueleticos_proeminentes":false,"linfonodomegalia_frequente":false,"febre_frequente":false,"sinais_sistemicos_inespecificos_comuns":true,"perda_peso_ou_caquexia_frequente":false,"diagnostico_por_exame_sorologico":false,"diagnostico_por_citologia_biopsia":false,"diagnostico_por_imagem_essencial":true,"diagnostico_laboratorial_bioquimico_essencial":true,"diagnostico_definitivo_requer_histopatologia":false,"teste_rapido_disponivel_rotina":true,"alteracoes_hematologicas_caracteristicas":false,"tratamento_cirurgico_indicado":false,"tratamento_quimioterapico_indicado":false,"tratamento_com_antimicrobianos_especificos":false,"tratamento_essencialmente_de_suporte":true,"tratamento_topico_frequente":false,"tratamento_exclusivamente_paliativo":false,"requer_tratamento_continuo_longo_prazo":false,"prognostico_favoravel":false,"doenca_potencialmente_fatal_sem_tratamento":true,"risco_recidiva_relevante":false,"cura_definitiva_possivel":true,"doenca_cronica_progressiva":false,"doenca_metabolica":false}'::jsonb, '{"letalidade_nao_tratada":85,"velocidade_progressao":90,"custo_complexidade_diagnostica":45,"impacto_qualidade_vida":80,"disseminacao_ambiente_coletivo":0,"relevancia_diferencial_rotina":55,"invasividade_tratamento_padrao":55,"impacto_economico_tratamento":60}'::jsonb)
on conflict (id) do nothing;

insert into public.doencas (id, nome, especie, sistema, dica, parametros_binarios, parametros_graduais)
values ('nefrolitiase_felina', 'Nefrolitíase (cálculos renais)', 'Felina', 'sistema_urinario', null, '{"zoonose":false,"doenca_viral":false,"doenca_bacteriana":false,"doenca_parasitaria":false,"doenca_fungica":false,"associada_uso_hormonios":false,"etiologia_hereditaria_genetica":false,"transmitida_por_vetores":false,"contagiosa_contato_direto":false,"transmissao_ambiental_fomites":false,"transmissao_vertical_transplacentaria":false,"requer_notificacao_obrigatoria":false,"maior_prevalencia_felinos":true,"predisposicao_racial_reconhecida":true,"maior_prevalencia_animais_idosos":true,"maior_prevalencia_filhotes_jovens":false,"predisposicao_femeas_nao_castradas":false,"associada_obesidade":false,"maior_prevalencia_ambientes_coletivos":false,"doenca_neoplasica":false,"causa_hemorragia":true,"lesao_caracteristicamente_multissistemica":false,"processo_inflamatorio_predominante":false,"lesao_potencialmente_metastatica":false,"causa_alteracao_degenerativa_cronica":false,"sinais_gastrointestinais_proeminentes":false,"sinais_respiratorios_proeminentes":false,"sinais_dermatologicos_proeminentes":false,"sinais_musculoesqueleticos_proeminentes":false,"linfonodomegalia_frequente":false,"febre_frequente":false,"sinais_sistemicos_inespecificos_comuns":false,"perda_peso_ou_caquexia_frequente":false,"diagnostico_por_exame_sorologico":false,"diagnostico_por_citologia_biopsia":false,"diagnostico_por_imagem_essencial":true,"diagnostico_laboratorial_bioquimico_essencial":false,"diagnostico_definitivo_requer_histopatologia":false,"teste_rapido_disponivel_rotina":false,"alteracoes_hematologicas_caracteristicas":false,"tratamento_cirurgico_indicado":true,"tratamento_quimioterapico_indicado":false,"tratamento_com_antimicrobianos_especificos":false,"tratamento_essencialmente_de_suporte":false,"tratamento_topico_frequente":false,"tratamento_exclusivamente_paliativo":false,"requer_tratamento_continuo_longo_prazo":true,"prognostico_favoravel":true,"doenca_potencialmente_fatal_sem_tratamento":false,"risco_recidiva_relevante":true,"cura_definitiva_possivel":true,"doenca_cronica_progressiva":false,"doenca_metabolica":false}'::jsonb, '{"letalidade_nao_tratada":15,"velocidade_progressao":20,"custo_complexidade_diagnostica":40,"impacto_qualidade_vida":35,"disseminacao_ambiente_coletivo":0,"relevancia_diferencial_rotina":35,"invasividade_tratamento_padrao":45,"impacto_economico_tratamento":45}'::jsonb)
on conflict (id) do nothing;

insert into public.doencas (id, nome, especie, sistema, dica, parametros_binarios, parametros_graduais)
values ('nefroblastoma_canino', 'Nefroblastoma (tumor de Wilms)', 'Canina', 'sistema_urinario', null, '{"zoonose":false,"doenca_viral":false,"doenca_bacteriana":false,"doenca_parasitaria":false,"doenca_fungica":false,"associada_uso_hormonios":false,"etiologia_hereditaria_genetica":false,"transmitida_por_vetores":false,"contagiosa_contato_direto":false,"transmissao_ambiental_fomites":false,"transmissao_vertical_transplacentaria":false,"requer_notificacao_obrigatoria":false,"maior_prevalencia_felinos":false,"predisposicao_racial_reconhecida":false,"maior_prevalencia_animais_idosos":false,"maior_prevalencia_filhotes_jovens":true,"predisposicao_femeas_nao_castradas":false,"associada_obesidade":false,"maior_prevalencia_ambientes_coletivos":false,"doenca_neoplasica":true,"causa_hemorragia":true,"lesao_caracteristicamente_multissistemica":false,"processo_inflamatorio_predominante":false,"lesao_potencialmente_metastatica":true,"causa_alteracao_degenerativa_cronica":false,"sinais_gastrointestinais_proeminentes":false,"sinais_respiratorios_proeminentes":false,"sinais_dermatologicos_proeminentes":false,"sinais_musculoesqueleticos_proeminentes":false,"linfonodomegalia_frequente":false,"febre_frequente":false,"sinais_sistemicos_inespecificos_comuns":false,"perda_peso_ou_caquexia_frequente":false,"diagnostico_por_exame_sorologico":false,"diagnostico_por_citologia_biopsia":true,"diagnostico_por_imagem_essencial":true,"diagnostico_laboratorial_bioquimico_essencial":false,"diagnostico_definitivo_requer_histopatologia":true,"teste_rapido_disponivel_rotina":false,"alteracoes_hematologicas_caracteristicas":false,"tratamento_cirurgico_indicado":true,"tratamento_quimioterapico_indicado":true,"tratamento_com_antimicrobianos_especificos":false,"tratamento_essencialmente_de_suporte":false,"tratamento_topico_frequente":false,"tratamento_exclusivamente_paliativo":false,"requer_tratamento_continuo_longo_prazo":false,"prognostico_favoravel":true,"doenca_potencialmente_fatal_sem_tratamento":true,"risco_recidiva_relevante":false,"cura_definitiva_possivel":true,"doenca_cronica_progressiva":false,"doenca_metabolica":false}'::jsonb, '{"letalidade_nao_tratada":55,"velocidade_progressao":40,"custo_complexidade_diagnostica":55,"impacto_qualidade_vida":40,"disseminacao_ambiente_coletivo":0,"relevancia_diferencial_rotina":20,"invasividade_tratamento_padrao":70,"impacto_economico_tratamento":55}'::jsonb)
on conflict (id) do nothing;

insert into public.doencas (id, nome, especie, sistema, dica, parametros_binarios, parametros_graduais)
values ('hidronefrose_equina', 'Hidronefrose', 'Equina', 'sistema_urinario', null, '{"zoonose":false,"doenca_viral":false,"doenca_bacteriana":false,"doenca_parasitaria":false,"doenca_fungica":false,"associada_uso_hormonios":false,"etiologia_hereditaria_genetica":false,"transmitida_por_vetores":false,"contagiosa_contato_direto":false,"transmissao_ambiental_fomites":false,"transmissao_vertical_transplacentaria":false,"requer_notificacao_obrigatoria":false,"maior_prevalencia_felinos":false,"predisposicao_racial_reconhecida":false,"maior_prevalencia_animais_idosos":false,"maior_prevalencia_filhotes_jovens":false,"predisposicao_femeas_nao_castradas":false,"associada_obesidade":false,"maior_prevalencia_ambientes_coletivos":false,"doenca_neoplasica":false,"causa_hemorragia":false,"lesao_caracteristicamente_multissistemica":false,"processo_inflamatorio_predominante":false,"lesao_potencialmente_metastatica":false,"causa_alteracao_degenerativa_cronica":true,"sinais_gastrointestinais_proeminentes":false,"sinais_respiratorios_proeminentes":false,"sinais_dermatologicos_proeminentes":false,"sinais_musculoesqueleticos_proeminentes":false,"linfonodomegalia_frequente":false,"febre_frequente":false,"sinais_sistemicos_inespecificos_comuns":false,"perda_peso_ou_caquexia_frequente":false,"diagnostico_por_exame_sorologico":false,"diagnostico_por_citologia_biopsia":false,"diagnostico_por_imagem_essencial":true,"diagnostico_laboratorial_bioquimico_essencial":false,"diagnostico_definitivo_requer_histopatologia":false,"teste_rapido_disponivel_rotina":false,"alteracoes_hematologicas_caracteristicas":false,"tratamento_cirurgico_indicado":true,"tratamento_quimioterapico_indicado":false,"tratamento_com_antimicrobianos_especificos":false,"tratamento_essencialmente_de_suporte":false,"tratamento_topico_frequente":false,"tratamento_exclusivamente_paliativo":false,"requer_tratamento_continuo_longo_prazo":false,"prognostico_favoravel":true,"doenca_potencialmente_fatal_sem_tratamento":false,"risco_recidiva_relevante":false,"cura_definitiva_possivel":true,"doenca_cronica_progressiva":true,"doenca_metabolica":false}'::jsonb, '{"letalidade_nao_tratada":15,"velocidade_progressao":20,"custo_complexidade_diagnostica":40,"impacto_qualidade_vida":25,"disseminacao_ambiente_coletivo":0,"relevancia_diferencial_rotina":15,"invasividade_tratamento_padrao":60,"impacto_economico_tratamento":55}'::jsonb)
on conflict (id) do nothing;

